USE [master]
GO
/****** Object:  Database [CommuMoney]    Script Date: 19/12/2021 01:05:13 ******/
CREATE DATABASE [CommuMoney]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CommuMoney', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CommuMoney.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CommuMoney_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CommuMoney_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [CommuMoney] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CommuMoney].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CommuMoney] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CommuMoney] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CommuMoney] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CommuMoney] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CommuMoney] SET ARITHABORT OFF 
GO
ALTER DATABASE [CommuMoney] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CommuMoney] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CommuMoney] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CommuMoney] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CommuMoney] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CommuMoney] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CommuMoney] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CommuMoney] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CommuMoney] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CommuMoney] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CommuMoney] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CommuMoney] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CommuMoney] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CommuMoney] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CommuMoney] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CommuMoney] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CommuMoney] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CommuMoney] SET RECOVERY FULL 
GO
ALTER DATABASE [CommuMoney] SET  MULTI_USER 
GO
ALTER DATABASE [CommuMoney] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CommuMoney] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CommuMoney] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CommuMoney] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CommuMoney] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CommuMoney] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'CommuMoney', N'ON'
GO
ALTER DATABASE [CommuMoney] SET QUERY_STORE = OFF
GO
USE [CommuMoney]
GO
/****** Object:  Table [dbo].[Depenses]    Script Date: 19/12/2021 01:05:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Depenses](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[id_personne] [int] NOT NULL,
	[id_projet] [int] NOT NULL,
	[montant] [float] NOT NULL,
 CONSTRAINT [PK_Depenses] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Personnes]    Script Date: 19/12/2021 01:05:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Personnes](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nom] [varchar](50) NOT NULL,
	[prenom] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Personnes] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Projet]    Script Date: 19/12/2021 01:05:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Projet](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nom] [varchar](50) NOT NULL,
	[id_personne] [int] NOT NULL,
	[total_montant] [float] NOT NULL,
	[moyenne] [float] NOT NULL,
	[date_soiree] [date] NULL,
 CONSTRAINT [PK_Projet] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Remboursement]    Script Date: 19/12/2021 01:05:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Remboursement](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[id_personne] [int] NOT NULL,
	[id_projet] [int] NOT NULL,
	[dette] [float] NOT NULL,
 CONSTRAINT [PK_Remboursement] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Depenses]  WITH CHECK ADD  CONSTRAINT [FK_Depenses_Personnes] FOREIGN KEY([id_personne])
REFERENCES [dbo].[Personnes] ([id])
GO
ALTER TABLE [dbo].[Depenses] CHECK CONSTRAINT [FK_Depenses_Personnes]
GO
ALTER TABLE [dbo].[Depenses]  WITH CHECK ADD  CONSTRAINT [FK_Depenses_Projet] FOREIGN KEY([id_projet])
REFERENCES [dbo].[Projet] ([id])
GO
ALTER TABLE [dbo].[Depenses] CHECK CONSTRAINT [FK_Depenses_Projet]
GO
ALTER TABLE [dbo].[Projet]  WITH CHECK ADD  CONSTRAINT [FK_Projet_Personnes] FOREIGN KEY([id_personne])
REFERENCES [dbo].[Personnes] ([id])
GO
ALTER TABLE [dbo].[Projet] CHECK CONSTRAINT [FK_Projet_Personnes]
GO
ALTER TABLE [dbo].[Remboursement]  WITH CHECK ADD  CONSTRAINT [FK_Remboursement_Personnes] FOREIGN KEY([id_personne])
REFERENCES [dbo].[Personnes] ([id])
GO
ALTER TABLE [dbo].[Remboursement] CHECK CONSTRAINT [FK_Remboursement_Personnes]
GO
ALTER TABLE [dbo].[Remboursement]  WITH CHECK ADD  CONSTRAINT [FK_Remboursement_Projet] FOREIGN KEY([id_projet])
REFERENCES [dbo].[Projet] ([id])
GO
ALTER TABLE [dbo].[Remboursement] CHECK CONSTRAINT [FK_Remboursement_Projet]
GO
USE [master]
GO
ALTER DATABASE [CommuMoney] SET  READ_WRITE 
GO
